export const DUMMY_GAMES = [
  {
    id: "1",
    team1Name: "Fotbal RxS",
    team1Logo: "./logo.jpg",
    team2Name: "C.S Viitorul Barlad",
    team2Logo: "./logo.jpg",
    name: "CUPA PLAY BACAU",
    time: "11",
    group: "GRUPA 2009",
    place: "Stadion",
  },
  {
    id: "2",
    team1Name: "Fotbal RxS",
    team1Logo: "./logo.jpg",
    team2Name: "C.S Viitorul Barlad",
    team2Logo: "./logo.jpg",
    name: "CUPA PLAY BACAU ",
    group: "GRUPA 2009",
    time: "11",
    place: "Stadion",
  },
  {
    id: "3",
    team1Name: "Fotbal RxS",
    team1Logo: "./logo.jpg",
    team2Name: "C.S Viitorul Barlad",
    team2Logo: "./logo.jpg",
    name: "CUPA PLAY BACAU ",
    time: "11",
    group: "GRUPA 2009",
    place: "Stadion",
  },
];
